version: '3'
services:

  server:
    build: .
    volumes:
      - ./:/go/src/github.com/tomekwlod/tes
      # - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /go/src/github.com/tomekwlod/tes
    env_file:
      - .env

  # importer:
  #   build: .
  #   volumes:
  #     - ./cmd/import:/app
  #     - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
  #   working_dir: /app
  #   env_file:
  #     - .env

  # nats:
  #   image: nats-streaming:0.11.2
  #   restart: on-failure